# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# zone.py
# Created on: 2016-09-21 09:33:51.00000
#   (generated by ArcGIS/ModelBuilder)
# Description:
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
import os
import functions


inlocation_species='C:\Users\Admin\Documents\Jen\Workspace\UseSites\ByProject'

workspaces = os.listdir(inlocation_species)
gdb_workspaces = [v for v in workspaces if v.endswith('.gdb')]
for i in gdb_workspaces:
        in_gdb = inlocation_species + os.sep + i
        print "\nWorking on geodatabase {0}".format(in_gdb)
        arcpy.env.workspace = in_gdb
        rast_list = arcpy.ListRasters()
        for raster_in in rast_list:
            arcpy.BuildRasterAttributeTable_management(raster_in, "Overwrite")
            print 'Build Attribute table completed for {0}'.format(raster_in)
